# Game parameters
WORLD_WIDTH = 5000
WORLD_HEIGHT = 5000

# Screen defaults (used if not overridden)
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Rendering
GRID_SIZE = 64

# Player defaults
PLAYER_SPEED = 300.0
PLAYER_RADIUS = 18
PLAYER_HP = 100
# Combat / attack defaults
PLAYER_DAMAGE = 15
PLAYER_ATTACK_COOLDOWN = 0.8
PLAYER_ATTACK_RANGE = 250
ARROW_SPEED = 800.0
ARROW_LIFETIME = 1.2
PLAYER_HIT_COOLDOWN = 0.5
